Update pr-validation.yaml
Use github.head_ref

diff --git a/.github/workflows/pr-validation.yaml b/.github/workflows/pr-validation.yaml
--- a/.github/workflows/pr-validation.yaml
+++ b/.github/workflows/pr-validation.yaml
@@ -17,13 +17,13 @@ jobs:
       - name: Check if workflows folder is modified
         id: check-workflows
         run: |
-          set -e  # Exit immediately if a command exits with a non-zero status
-          git fetch --no-tags --depth=2 https://github.com/${{ github.event.pull_request.head.repo.full_name }} ${{ github.head_ref }}
-          if git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} | grep -q '^.github/workflows/'; then
+            set -e  # Exit immediately if a command exits with a non-zero status
+            git fetch --no-tags --depth=2 origin ${{ github.head_ref }}
+            if git diff --name-only origin/${{ github.base_ref }} ${{ github.head_ref }} | grep -q '^.github/workflows/'; then
             echo "workflows_modified=true" >> $GITHUB_ENV
-          else
+            else
             echo "workflows_modified=false" >> $GITHUB_ENV
-          fi
+            fi
 
       - name: "Fail if workflows folder is not checked"
         run: |
