Use pull_request_target and add permissions, including pr-origin (instead of base)

diff --git a/.github/workflows/pr-validation.yaml b/.github/workflows/pr-validation.yaml
--- a/.github/workflows/pr-validation.yaml
+++ b/.github/workflows/pr-validation.yaml
@@ -1,8 +1,12 @@
 name: Validate Pull Request
 
 on:
-  pull_request:
+  pull_request_target: # Secure that it's using the workflow file from the base branch; not the PR
     types: [opened, synchronize, reopened]
+
+permissions:
+  issues: write
+  pull-requests: write
 
 jobs:
   validate-pr:
@@ -17,13 +21,15 @@ jobs:
       - name: Check if workflows folder is modified
         id: check-workflows
         run: |
-          set -e  # Exit immediately if a command exits with a non-zero status
-          git fetch --no-tags --depth=2 origin ${{ github.base_ref }} ${{ github.head_ref }}
-          if git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} | grep -q '^.github/workflows/'; then
+            set -e  # Exit immediately if a command exits with a non-zero status
+            git remote add pr-origin "${{ github.event.pull_request.head.repo.clone_url }}"
+            git fetch pr-origin "${{ github.event.pull_request.head.ref }}"
+            git fetch origin "${{ github.base_ref }}"
+            if git diff --name-only "origin/${{ github.base_ref }}" "pr-origin/${{ github.event.pull_request.head.ref }}" | grep -q '^.github/workflows/'; then
             echo "workflows_modified=true" >> $GITHUB_ENV
-          else
+            else
             echo "workflows_modified=false" >> $GITHUB_ENV
-          fi
+            fi
 
       - name: "Fail if workflows folder is not checked"
         run: |
