Add dot to comment

diff --git a/.github/workflows/pr-validation.yaml b/.github/workflows/pr-validation.yaml
--- a/.github/workflows/pr-validation.yaml
+++ b/.github/workflows/pr-validation.yaml
@@ -17,7 +17,7 @@ jobs:
       - name: Check if workflows folder is modified
         id: check-workflows
         run: |
-          set -e  # Exit immediately if a command exits with a non-zero status
+          set -e  # Exit immediately if a command exits with a non-zero status.
           git fetch --no-tags --depth=2 origin ${{ github.base_ref }} ${{ github.head_ref }}
           if git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} | grep -q '^.github/workflows/'; then
             echo "workflows_modified=true" >> $GITHUB_ENV
